name: main
on:
  push:
    branches:
      - main
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install dependencies
        run: pnpm ci
      - name: Run typecheck
        run: pnpm run typecheck
