name: main

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    name: Build and Test

    timeout-minutes: 10

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v4
        with:
          version: 9.4.0

      - run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      - id: nvm

      - uses: actions/setup-node@v4
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run lint
      - run: pnpm run test
